admin_pages:
    resource: "@AdminPagesBundle/Resources/config/routing.yml"
    prefix:   /

user_pages:
    resource: "@UserPagesBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }
logout:
    path: /login